// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type File struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	MimeType       string         `json:"mime_type"`
	Size           int64          `json:"size"`
	StorageKey     string         `json:"storage_key"`
	Extension      sql.NullString `json:"extension"`
	Starred        bool           `json:"starred"`
	Deleted        bool           `json:"deleted"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	ParentFolderID sql.NullString `json:"parent_folder_id"`
	OwnerID        string         `json:"owner_id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type Folder struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Starred        bool           `json:"starred"`
	Deleted        bool           `json:"deleted"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	ParentFolderID sql.NullString `json:"parent_folder_id"`
	OwnerID        string         `json:"owner_id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
