// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createFile = `-- name: CreateFile :one

INSERT INTO files (id, name, mime_type, size, storage_key, extension, parent_folder_id, owner_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, mime_type, size, storage_key, extension, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at, thumbnail_key
`

type CreateFileParams struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	MimeType       string         `json:"mime_type"`
	Size           int64          `json:"size"`
	StorageKey     string         `json:"storage_key"`
	Extension      sql.NullString `json:"extension"`
	ParentFolderID sql.NullString `json:"parent_folder_id"`
	OwnerID        string         `json:"owner_id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

// ============================================================================
// File Queries
// ============================================================================
func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.ID,
		arg.Name,
		arg.MimeType,
		arg.Size,
		arg.StorageKey,
		arg.Extension,
		arg.ParentFolderID,
		arg.OwnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MimeType,
		&i.Size,
		&i.StorageKey,
		&i.Extension,
		&i.Starred,
		&i.Deleted,
		&i.DeletedAt,
		&i.ParentFolderID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailKey,
	)
	return i, err
}

const createFolder = `-- name: CreateFolder :one

INSERT INTO folders (id, name, parent_folder_id, owner_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at
`

type CreateFolderParams struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	ParentFolderID sql.NullString `json:"parent_folder_id"`
	OwnerID        string         `json:"owner_id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

// ============================================================================
// Folder Queries
// ============================================================================
func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, createFolder,
		arg.ID,
		arg.Name,
		arg.ParentFolderID,
		arg.OwnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Starred,
		&i.Deleted,
		&i.DeletedAt,
		&i.ParentFolderID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, email, name, password_hash, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, email, name, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// ============================================================================
// Auth Queries
// ============================================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExistingFileNamesInParent = `-- name: GetExistingFileNamesInParent :many
SELECT name FROM files
WHERE owner_id = ? AND parent_folder_id = ? AND deleted = false
`

type GetExistingFileNamesInParentParams struct {
	OwnerID        string         `json:"owner_id"`
	ParentFolderID sql.NullString `json:"parent_folder_id"`
}

func (q *Queries) GetExistingFileNamesInParent(ctx context.Context, arg GetExistingFileNamesInParentParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getExistingFileNamesInParent, arg.OwnerID, arg.ParentFolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingFileNamesInRoot = `-- name: GetExistingFileNamesInRoot :many
SELECT name FROM files
WHERE owner_id = ? AND parent_folder_id IS NULL AND deleted = false
`

func (q *Queries) GetExistingFileNamesInRoot(ctx context.Context, ownerID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getExistingFileNamesInRoot, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingFolderNamesInParent = `-- name: GetExistingFolderNamesInParent :many
SELECT name FROM folders
WHERE owner_id = ? AND parent_folder_id = ? AND deleted = false
`

type GetExistingFolderNamesInParentParams struct {
	OwnerID        string         `json:"owner_id"`
	ParentFolderID sql.NullString `json:"parent_folder_id"`
}

func (q *Queries) GetExistingFolderNamesInParent(ctx context.Context, arg GetExistingFolderNamesInParentParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getExistingFolderNamesInParent, arg.OwnerID, arg.ParentFolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingFolderNamesInRoot = `-- name: GetExistingFolderNamesInRoot :many
SELECT name FROM folders
WHERE owner_id = ? AND parent_folder_id IS NULL AND deleted = false
`

func (q *Queries) GetExistingFolderNamesInRoot(ctx context.Context, ownerID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getExistingFolderNamesInRoot, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, name, mime_type, size, storage_key, extension, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at, thumbnail_key FROM files
WHERE id = ?
`

func (q *Queries) GetFileByID(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MimeType,
		&i.Size,
		&i.StorageKey,
		&i.Extension,
		&i.Starred,
		&i.Deleted,
		&i.DeletedAt,
		&i.ParentFolderID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailKey,
	)
	return i, err
}

const getFileByIDAndOwner = `-- name: GetFileByIDAndOwner :one
SELECT id, name, mime_type, size, storage_key, extension, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at, thumbnail_key FROM files
WHERE id = ? AND owner_id = ?
`

type GetFileByIDAndOwnerParams struct {
	ID      string `json:"id"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) GetFileByIDAndOwner(ctx context.Context, arg GetFileByIDAndOwnerParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByIDAndOwner, arg.ID, arg.OwnerID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MimeType,
		&i.Size,
		&i.StorageKey,
		&i.Extension,
		&i.Starred,
		&i.Deleted,
		&i.DeletedAt,
		&i.ParentFolderID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailKey,
	)
	return i, err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, name, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at FROM folders
WHERE id = ?
`

func (q *Queries) GetFolderByID(ctx context.Context, id string) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Starred,
		&i.Deleted,
		&i.DeletedAt,
		&i.ParentFolderID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderByIDAndOwner = `-- name: GetFolderByIDAndOwner :one
SELECT id, name, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at FROM folders
WHERE id = ? AND owner_id = ?
`

type GetFolderByIDAndOwnerParams struct {
	ID      string `json:"id"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) GetFolderByIDAndOwner(ctx context.Context, arg GetFolderByIDAndOwnerParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolderByIDAndOwner, arg.ID, arg.OwnerID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Starred,
		&i.Deleted,
		&i.DeletedAt,
		&i.ParentFolderID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderDescendantIDs = `-- name: GetFolderDescendantIDs :many
WITH RECURSIVE folder_tree AS (
    SELECT folders.id AS id FROM folders WHERE folders.id = ? AND folders.owner_id = ?
    UNION ALL
    SELECT f.id AS id FROM folders f
    JOIN folder_tree ft ON f.parent_folder_id = ft.id
)
SELECT folder_tree.id FROM folder_tree
`

type GetFolderDescendantIDsParams struct {
	ID      string `json:"id"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) GetFolderDescendantIDs(ctx context.Context, arg GetFolderDescendantIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getFolderDescendantIDs, arg.ID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStorageKeysByFolderID = `-- name: GetStorageKeysByFolderID :many
SELECT storage_key FROM files
WHERE parent_folder_id = ? AND owner_id = ?
`

type GetStorageKeysByFolderIDParams struct {
	ParentFolderID sql.NullString `json:"parent_folder_id"`
	OwnerID        string         `json:"owner_id"`
}

func (q *Queries) GetStorageKeysByFolderID(ctx context.Context, arg GetStorageKeysByFolderIDParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getStorageKeysByFolderID, arg.ParentFolderID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalStorageUsedByOwner = `-- name: GetTotalStorageUsedByOwner :one
SELECT COALESCE(SUM(size), 0) AS total_size
FROM files
WHERE owner_id = ? AND deleted = false
`

func (q *Queries) GetTotalStorageUsedByOwner(ctx context.Context, ownerID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalStorageUsedByOwner, ownerID)
	var total_size interface{}
	err := row.Scan(&total_size)
	return total_size, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, created_at, updated_at FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, created_at, updated_at FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFilesByParent = `-- name: ListFilesByParent :many
SELECT id, name, mime_type, size, storage_key, extension, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at, thumbnail_key FROM files
WHERE owner_id = ? AND parent_folder_id = ? AND deleted = false
ORDER BY name ASC
`

type ListFilesByParentParams struct {
	OwnerID        string         `json:"owner_id"`
	ParentFolderID sql.NullString `json:"parent_folder_id"`
}

func (q *Queries) ListFilesByParent(ctx context.Context, arg ListFilesByParentParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByParent, arg.OwnerID, arg.ParentFolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MimeType,
			&i.Size,
			&i.StorageKey,
			&i.Extension,
			&i.Starred,
			&i.Deleted,
			&i.DeletedAt,
			&i.ParentFolderID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbnailKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersByParent = `-- name: ListFoldersByParent :many
SELECT id, name, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at FROM folders
WHERE owner_id = ? AND parent_folder_id = ? AND deleted = false
ORDER BY name ASC
`

type ListFoldersByParentParams struct {
	OwnerID        string         `json:"owner_id"`
	ParentFolderID sql.NullString `json:"parent_folder_id"`
}

func (q *Queries) ListFoldersByParent(ctx context.Context, arg ListFoldersByParentParams) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFoldersByParent, arg.OwnerID, arg.ParentFolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Starred,
			&i.Deleted,
			&i.DeletedAt,
			&i.ParentFolderID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFiles = `-- name: ListRootFiles :many
SELECT id, name, mime_type, size, storage_key, extension, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at, thumbnail_key FROM files
WHERE owner_id = ? AND parent_folder_id IS NULL AND deleted = false
ORDER BY name ASC
`

func (q *Queries) ListRootFiles(ctx context.Context, ownerID string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listRootFiles, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MimeType,
			&i.Size,
			&i.StorageKey,
			&i.Extension,
			&i.Starred,
			&i.Deleted,
			&i.DeletedAt,
			&i.ParentFolderID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbnailKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFolders = `-- name: ListRootFolders :many
SELECT id, name, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at FROM folders
WHERE owner_id = ? AND parent_folder_id IS NULL AND deleted = false
ORDER BY name ASC
`

func (q *Queries) ListRootFolders(ctx context.Context, ownerID string) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listRootFolders, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Starred,
			&i.Deleted,
			&i.DeletedAt,
			&i.ParentFolderID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarredFiles = `-- name: ListStarredFiles :many
SELECT id, name, mime_type, size, storage_key, extension, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at, thumbnail_key FROM files
WHERE owner_id = ? AND starred = true AND deleted = false
ORDER BY name ASC
`

func (q *Queries) ListStarredFiles(ctx context.Context, ownerID string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listStarredFiles, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MimeType,
			&i.Size,
			&i.StorageKey,
			&i.Extension,
			&i.Starred,
			&i.Deleted,
			&i.DeletedAt,
			&i.ParentFolderID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbnailKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarredFolders = `-- name: ListStarredFolders :many
SELECT id, name, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at FROM folders
WHERE owner_id = ? AND starred = true AND deleted = false
ORDER BY name ASC
`

func (q *Queries) ListStarredFolders(ctx context.Context, ownerID string) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listStarredFolders, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Starred,
			&i.Deleted,
			&i.DeletedAt,
			&i.ParentFolderID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashFiles = `-- name: ListTrashFiles :many
SELECT id, name, mime_type, size, storage_key, extension, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at, thumbnail_key FROM files
WHERE owner_id = ? AND deleted = true
ORDER BY deleted_at DESC
`

func (q *Queries) ListTrashFiles(ctx context.Context, ownerID string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listTrashFiles, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MimeType,
			&i.Size,
			&i.StorageKey,
			&i.Extension,
			&i.Starred,
			&i.Deleted,
			&i.DeletedAt,
			&i.ParentFolderID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbnailKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashFolders = `-- name: ListTrashFolders :many
SELECT id, name, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at FROM folders
WHERE owner_id = ? AND deleted = true
ORDER BY deleted_at DESC
`

func (q *Queries) ListTrashFolders(ctx context.Context, ownerID string) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listTrashFolders, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Starred,
			&i.Deleted,
			&i.DeletedAt,
			&i.ParentFolderID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFile = `-- name: MoveFile :one
UPDATE files
SET parent_folder_id = ?, updated_at = ?
WHERE id = ? AND owner_id = ?
RETURNING id, name, mime_type, size, storage_key, extension, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at, thumbnail_key
`

type MoveFileParams struct {
	ParentFolderID sql.NullString `json:"parent_folder_id"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ID             string         `json:"id"`
	OwnerID        string         `json:"owner_id"`
}

func (q *Queries) MoveFile(ctx context.Context, arg MoveFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, moveFile,
		arg.ParentFolderID,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MimeType,
		&i.Size,
		&i.StorageKey,
		&i.Extension,
		&i.Starred,
		&i.Deleted,
		&i.DeletedAt,
		&i.ParentFolderID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailKey,
	)
	return i, err
}

const moveFolder = `-- name: MoveFolder :one
UPDATE folders
SET parent_folder_id = ?, updated_at = ?
WHERE id = ? AND owner_id = ?
RETURNING id, name, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at
`

type MoveFolderParams struct {
	ParentFolderID sql.NullString `json:"parent_folder_id"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ID             string         `json:"id"`
	OwnerID        string         `json:"owner_id"`
}

func (q *Queries) MoveFolder(ctx context.Context, arg MoveFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, moveFolder,
		arg.ParentFolderID,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerID,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Starred,
		&i.Deleted,
		&i.DeletedAt,
		&i.ParentFolderID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const permanentDeleteFile = `-- name: PermanentDeleteFile :exec
DELETE FROM files
WHERE id = ? AND owner_id = ?
`

type PermanentDeleteFileParams struct {
	ID      string `json:"id"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) PermanentDeleteFile(ctx context.Context, arg PermanentDeleteFileParams) error {
	_, err := q.db.ExecContext(ctx, permanentDeleteFile, arg.ID, arg.OwnerID)
	return err
}

const permanentDeleteFolder = `-- name: PermanentDeleteFolder :exec
DELETE FROM folders
WHERE id = ? AND owner_id = ?
`

type PermanentDeleteFolderParams struct {
	ID      string `json:"id"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) PermanentDeleteFolder(ctx context.Context, arg PermanentDeleteFolderParams) error {
	_, err := q.db.ExecContext(ctx, permanentDeleteFolder, arg.ID, arg.OwnerID)
	return err
}

const renameFile = `-- name: RenameFile :one
UPDATE files
SET name = ?, extension = ?, updated_at = ?
WHERE id = ? AND owner_id = ?
RETURNING id, name, mime_type, size, storage_key, extension, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at, thumbnail_key
`

type RenameFileParams struct {
	Name      string         `json:"name"`
	Extension sql.NullString `json:"extension"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
	OwnerID   string         `json:"owner_id"`
}

func (q *Queries) RenameFile(ctx context.Context, arg RenameFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, renameFile,
		arg.Name,
		arg.Extension,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MimeType,
		&i.Size,
		&i.StorageKey,
		&i.Extension,
		&i.Starred,
		&i.Deleted,
		&i.DeletedAt,
		&i.ParentFolderID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailKey,
	)
	return i, err
}

const renameFolder = `-- name: RenameFolder :one
UPDATE folders
SET name = ?, updated_at = ?
WHERE id = ? AND owner_id = ?
RETURNING id, name, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at
`

type RenameFolderParams struct {
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
	OwnerID   string    `json:"owner_id"`
}

func (q *Queries) RenameFolder(ctx context.Context, arg RenameFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, renameFolder,
		arg.Name,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerID,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Starred,
		&i.Deleted,
		&i.DeletedAt,
		&i.ParentFolderID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const restoreFile = `-- name: RestoreFile :one
UPDATE files
SET deleted = false, deleted_at = NULL, updated_at = ?
WHERE id = ? AND owner_id = ?
RETURNING id, name, mime_type, size, storage_key, extension, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at, thumbnail_key
`

type RestoreFileParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
	OwnerID   string    `json:"owner_id"`
}

func (q *Queries) RestoreFile(ctx context.Context, arg RestoreFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, restoreFile, arg.UpdatedAt, arg.ID, arg.OwnerID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MimeType,
		&i.Size,
		&i.StorageKey,
		&i.Extension,
		&i.Starred,
		&i.Deleted,
		&i.DeletedAt,
		&i.ParentFolderID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailKey,
	)
	return i, err
}

const restoreFolder = `-- name: RestoreFolder :one
UPDATE folders
SET deleted = false, deleted_at = NULL, updated_at = ?
WHERE id = ? AND owner_id = ?
RETURNING id, name, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at
`

type RestoreFolderParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
	OwnerID   string    `json:"owner_id"`
}

func (q *Queries) RestoreFolder(ctx context.Context, arg RestoreFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, restoreFolder, arg.UpdatedAt, arg.ID, arg.OwnerID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Starred,
		&i.Deleted,
		&i.DeletedAt,
		&i.ParentFolderID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchFilesByName = `-- name: SearchFilesByName :many
SELECT id, name, mime_type, size, storage_key, extension, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at, thumbnail_key FROM files
WHERE owner_id = ? AND deleted = false AND name LIKE ?
ORDER BY name ASC
`

type SearchFilesByNameParams struct {
	OwnerID string `json:"owner_id"`
	Name    string `json:"name"`
}

func (q *Queries) SearchFilesByName(ctx context.Context, arg SearchFilesByNameParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, searchFilesByName, arg.OwnerID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MimeType,
			&i.Size,
			&i.StorageKey,
			&i.Extension,
			&i.Starred,
			&i.Deleted,
			&i.DeletedAt,
			&i.ParentFolderID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThumbnailKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFileStarred = `-- name: SetFileStarred :one
UPDATE files
SET starred = ?, updated_at = ?
WHERE id = ? AND owner_id = ?
RETURNING id, name, mime_type, size, storage_key, extension, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at, thumbnail_key
`

type SetFileStarredParams struct {
	Starred   bool      `json:"starred"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
	OwnerID   string    `json:"owner_id"`
}

func (q *Queries) SetFileStarred(ctx context.Context, arg SetFileStarredParams) (File, error) {
	row := q.db.QueryRowContext(ctx, setFileStarred,
		arg.Starred,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MimeType,
		&i.Size,
		&i.StorageKey,
		&i.Extension,
		&i.Starred,
		&i.Deleted,
		&i.DeletedAt,
		&i.ParentFolderID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailKey,
	)
	return i, err
}

const setFileThumbnailKey = `-- name: SetFileThumbnailKey :exec
UPDATE files
SET thumbnail_key = ?
WHERE id = ?
`

type SetFileThumbnailKeyParams struct {
	ThumbnailKey sql.NullString `json:"thumbnail_key"`
	ID           string         `json:"id"`
}

func (q *Queries) SetFileThumbnailKey(ctx context.Context, arg SetFileThumbnailKeyParams) error {
	_, err := q.db.ExecContext(ctx, setFileThumbnailKey, arg.ThumbnailKey, arg.ID)
	return err
}

const setFolderStarred = `-- name: SetFolderStarred :one
UPDATE folders
SET starred = ?, updated_at = ?
WHERE id = ? AND owner_id = ?
RETURNING id, name, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at
`

type SetFolderStarredParams struct {
	Starred   bool      `json:"starred"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
	OwnerID   string    `json:"owner_id"`
}

func (q *Queries) SetFolderStarred(ctx context.Context, arg SetFolderStarredParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, setFolderStarred,
		arg.Starred,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerID,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Starred,
		&i.Deleted,
		&i.DeletedAt,
		&i.ParentFolderID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteFile = `-- name: SoftDeleteFile :one
UPDATE files
SET deleted = true, deleted_at = ?, updated_at = ?
WHERE id = ? AND owner_id = ?
RETURNING id, name, mime_type, size, storage_key, extension, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at, thumbnail_key
`

type SoftDeleteFileParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
	OwnerID   string       `json:"owner_id"`
}

func (q *Queries) SoftDeleteFile(ctx context.Context, arg SoftDeleteFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, softDeleteFile,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MimeType,
		&i.Size,
		&i.StorageKey,
		&i.Extension,
		&i.Starred,
		&i.Deleted,
		&i.DeletedAt,
		&i.ParentFolderID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailKey,
	)
	return i, err
}

const softDeleteFilesInFolder = `-- name: SoftDeleteFilesInFolder :exec
UPDATE files
SET deleted = true, deleted_at = ?, updated_at = ?
WHERE parent_folder_id = ? AND owner_id = ?
`

type SoftDeleteFilesInFolderParams struct {
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ParentFolderID sql.NullString `json:"parent_folder_id"`
	OwnerID        string         `json:"owner_id"`
}

func (q *Queries) SoftDeleteFilesInFolder(ctx context.Context, arg SoftDeleteFilesInFolderParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteFilesInFolder,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ParentFolderID,
		arg.OwnerID,
	)
	return err
}

const softDeleteFolder = `-- name: SoftDeleteFolder :one
UPDATE folders
SET deleted = true, deleted_at = ?, updated_at = ?
WHERE id = ? AND owner_id = ?
RETURNING id, name, starred, deleted, deleted_at, parent_folder_id, owner_id, created_at, updated_at
`

type SoftDeleteFolderParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
	OwnerID   string       `json:"owner_id"`
}

func (q *Queries) SoftDeleteFolder(ctx context.Context, arg SoftDeleteFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, softDeleteFolder,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerID,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Starred,
		&i.Deleted,
		&i.DeletedAt,
		&i.ParentFolderID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteFolderByID = `-- name: SoftDeleteFolderByID :exec
UPDATE folders
SET deleted = true, deleted_at = ?, updated_at = ?
WHERE id = ? AND owner_id = ?
`

type SoftDeleteFolderByIDParams struct {
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
	OwnerID   string       `json:"owner_id"`
}

func (q *Queries) SoftDeleteFolderByID(ctx context.Context, arg SoftDeleteFolderByIDParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteFolderByID,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerID,
	)
	return err
}
